[package]
name = "solana-counter-program"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "1.18.12"

[dev-dependencies]
solana-sdk = "1.18.12"

[features]
default = ["std"]
std = []

[build]
rustflags = ["-Z", "next-lockfile-bump"]